<?php

namespace Zacksleo\SuningSdk\Fake\Custom;

/**
 * Custom Class
 *
 * @property \Zacksleo\SuningSdk\Fake\Custom\Abnormal $abnormal
 * @property \Zacksleo\SuningSdk\Fake\Custom\Atmopic $atmopic
 * @property \Zacksleo\SuningSdk\Fake\Custom\Featureword $featureword
 * @property \Zacksleo\SuningSdk\Fake\Custom\Price $price
 * @property \Zacksleo\SuningSdk\Fake\Custom\Getproductcode $getproductcode
 * @property \Zacksleo\SuningSdk\Fake\Custom\Norm $norm
 * @property \Zacksleo\SuningSdk\Fake\Custom\Videoinfo $videoinfo
 * @property \Zacksleo\SuningSdk\Fake\Custom\Otoinfo $otoinfo
 * @property \Zacksleo\SuningSdk\Fake\Custom\Storegroup $storegroup
 * @property \Zacksleo\SuningSdk\Fake\Custom\Lsyprice $lsyprice
 * @property \Zacksleo\SuningSdk\Fake\Custom\Picfiles $picfiles
 * @property \Zacksleo\SuningSdk\Fake\Custom\Bookitem $bookitem
 * @property \Zacksleo\SuningSdk\Fake\Custom\Newbrand $newbrand
 * @property \Zacksleo\SuningSdk\Fake\Custom\Culitem $culitem
 * @property \Zacksleo\SuningSdk\Fake\Custom\Culitemcontentrevise $culitemcontentrevise
 * @property \Zacksleo\SuningSdk\Fake\Custom\Product $product
 * @property \Zacksleo\SuningSdk\Fake\Custom\Culitemcontents $culitemcontents
 * @property \Zacksleo\SuningSdk\Fake\Custom\Judgeproduct $judgeproduct
 * @property \Zacksleo\SuningSdk\Fake\Custom\Culitemdetail $culitemdetail
 * @property \Zacksleo\SuningSdk\Fake\Custom\Vedio $vedio
 * @property \Zacksleo\SuningSdk\Fake\Custom\Bookmainproduct $bookmainproduct
 * @property \Zacksleo\SuningSdk\Fake\Custom\Categoryredict $categoryredict
 * @property \Zacksleo\SuningSdk\Fake\Custom\Category $category
 * @property \Zacksleo\SuningSdk\Fake\Custom\Book $book
 * @property \Zacksleo\SuningSdk\Fake\Custom\Productdetail $productdetail
 * @property \Zacksleo\SuningSdk\Fake\Custom\Item $item
 * @property \Zacksleo\SuningSdk\Fake\Custom\Itemdetail $itemdetail
 * @property \Zacksleo\SuningSdk\Fake\Custom\Itemparameters $itemparameters
 * @property \Zacksleo\SuningSdk\Fake\Custom\Itemcontents $itemcontents
 * @property \Zacksleo\SuningSdk\Fake\Custom\Itemsale $itemsale
 * @property \Zacksleo\SuningSdk\Fake\Custom\Shelves $shelves
 * @property \Zacksleo\SuningSdk\Fake\Custom\Childitem $childitem
 * @property \Zacksleo\SuningSdk\Fake\Custom\Pic $pic
 * @property \Zacksleo\SuningSdk\Fake\Custom\Mainproduct $mainproduct
 * @property \Zacksleo\SuningSdk\Fake\Custom\Moduletemplet $moduletemplet
 * @property \Zacksleo\SuningSdk\Fake\Custom\Mobilerecommend $mobilerecommend
 * @property \Zacksleo\SuningSdk\Fake\Custom\Mobilesequence $mobilesequence
 * @property \Zacksleo\SuningSdk\Fake\Custom\Npic $npic
 * @property \Zacksleo\SuningSdk\Fake\Custom\Invaddress $invaddress
 * @property \Zacksleo\SuningSdk\Fake\Custom\Code $code
 * @property \Zacksleo\SuningSdk\Fake\Custom\Inventory $inventory
 * @property \Zacksleo\SuningSdk\Fake\Custom\Parallelinvaddress $parallelinvaddress
 * @property \Zacksleo\SuningSdk\Fake\Custom\Parallelinventory $parallelinventory
 * @property \Zacksleo\SuningSdk\Fake\Custom\Parallelinvarea $parallelinvarea
 * @property \Zacksleo\SuningSdk\Fake\Custom\Nation $nation
 * @property \Zacksleo\SuningSdk\Fake\Custom\Productsalearea $productsalearea
 * @property \Zacksleo\SuningSdk\Fake\Custom\City $city
 * @property \Zacksleo\SuningSdk\Fake\Custom\Saleareatemplate $saleareatemplate
 * @property \Zacksleo\SuningSdk\Fake\Custom\Saleareatemplateitemgroup $saleareatemplateitemgroup
 * @property \Zacksleo\SuningSdk\Fake\Custom\Freighttemplate $freighttemplate
 * @property \Zacksleo\SuningSdk\Fake\Custom\Returnorder $returnorder
 * @property \Zacksleo\SuningSdk\Fake\Custom\Deliverynew $deliverynew
 * @property \Zacksleo\SuningSdk\Fake\Custom\Ordmodtime $ordmodtime
 * @property \Zacksleo\SuningSdk\Fake\Custom\Orders $orders
 * @property \Zacksleo\SuningSdk\Fake\Custom\Dicwhole $dicwhole
 * @property \Zacksleo\SuningSdk\Fake\Custom\Dicsingle $dicsingle
 * @property \Zacksleo\SuningSdk\Fake\Custom\Logisticsnews $logisticsnews
 * @property \Zacksleo\SuningSdk\Fake\Custom\Virtual $virtual
 * @property \Zacksleo\SuningSdk\Fake\Custom\Dsrinfo $dsrinfo
 * @property \Zacksleo\SuningSdk\Fake\Custom\Merorderdirect $merorderdirect
 * @property \Zacksleo\SuningSdk\Fake\Custom\Tickets $tickets
 * @property \Zacksleo\SuningSdk\Fake\Custom\Historyorder $historyorder
 * @property \Zacksleo\SuningSdk\Fake\Custom\Order $order
 * @property \Zacksleo\SuningSdk\Fake\Custom\Ordercode $ordercode
 * @property \Zacksleo\SuningSdk\Fake\Custom\Ordernote $ordernote
 * @property \Zacksleo\SuningSdk\Fake\Custom\Orderdelivery $orderdelivery
 * @property \Zacksleo\SuningSdk\Fake\Custom\Orderdelay $orderdelay
 * @property \Zacksleo\SuningSdk\Fake\Custom\Ordercountdown $ordercountdown
 * @property \Zacksleo\SuningSdk\Fake\Custom\Logisticcompany $logisticcompany
 * @property \Zacksleo\SuningSdk\Fake\Custom\Ord $ord
 * @property \Zacksleo\SuningSdk\Fake\Custom\Unpaidorder $unpaidorder
 * @property \Zacksleo\SuningSdk\Fake\Custom\Orderselfdist $orderselfdist
 * @property \Zacksleo\SuningSdk\Fake\Custom\Comphandle $comphandle
 * @property \Zacksleo\SuningSdk\Fake\Custom\Complaint $complaint
 * @property \Zacksleo\SuningSdk\Fake\Custom\Seaorderdelivery $seaorderdelivery
 * @property \Zacksleo\SuningSdk\Fake\Custom\Packageorderdeliver $packageorderdeliver
 * @property \Zacksleo\SuningSdk\Fake\Custom\Bsseaorderdeclare $bsseaorderdeclare
 * @property \Zacksleo\SuningSdk\Fake\Custom\Seaorderdeclare $seaorderdeclare
 * @property \Zacksleo\SuningSdk\Fake\Custom\Hisorderevaluate $hisorderevaluate
 * @property \Zacksleo\SuningSdk\Fake\Custom\Orderevaluate $orderevaluate
 * @property \Zacksleo\SuningSdk\Fake\Custom\Replycmreview $replycmreview
 * @property \Zacksleo\SuningSdk\Fake\Custom\Transportfee $transportfee
 * @property \Zacksleo\SuningSdk\Fake\Custom\Electronicinvoice $electronicinvoice
 * @property \Zacksleo\SuningSdk\Fake\Custom\Batchrejected $batchrejected
 * @property \Zacksleo\SuningSdk\Fake\Custom\BatchrejectedOrd $batchrejectedOrd
 * @property \Zacksleo\SuningSdk\Fake\Custom\Singlerejected $singlerejected
 * @property \Zacksleo\SuningSdk\Fake\Custom\Agreerejected $agreerejected
 * @property \Zacksleo\SuningSdk\Fake\Custom\Disagreerejected $disagreerejected
 * @property \Zacksleo\SuningSdk\Fake\Custom\Disagreerefund $disagreerefund
 * @property \Zacksleo\SuningSdk\Fake\Custom\Delayrefund $delayrefund
 * @property \Zacksleo\SuningSdk\Fake\Custom\Rejectedord $rejectedord
 * @property \Zacksleo\SuningSdk\Fake\Custom\Agreerefund $agreerefund
 * @property \Zacksleo\SuningSdk\Fake\Custom\Verifycode $verifycode
 * @property \Zacksleo\SuningSdk\Fake\Custom\Shopcategory $shopcategory
 * @property \Zacksleo\SuningSdk\Fake\Custom\Shopaddfavorite $shopaddfavorite
 * @property \Zacksleo\SuningSdk\Fake\Custom\Shopcategoryitem $shopcategoryitem
 * @property \Zacksleo\SuningSdk\Fake\Custom\Shopinfo $shopinfo
 * @property \Zacksleo\SuningSdk\Fake\Custom\Logisticsstatus $logisticsstatus
 * @property \Zacksleo\SuningSdk\Fake\Custom\Invbalance $invbalance
 * @property \Zacksleo\SuningSdk\Fake\Custom\Invmacinfo $invmacinfo
 * @property \Zacksleo\SuningSdk\Fake\Custom\Invoiceinfo $invoiceinfo
 * @property \Zacksleo\SuningSdk\Fake\Custom\Invoverstock $invoverstock
 * @property \Zacksleo\SuningSdk\Fake\Custom\Invorder $invorder
 * @property \Zacksleo\SuningSdk\Fake\Custom\Pzxxdatainfo $pzxxdatainfo
 * @property \Zacksleo\SuningSdk\Fake\Custom\Storage $storage
 * @property \Zacksleo\SuningSdk\Fake\Custom\Memintegral $memintegral
 * @property \Zacksleo\SuningSdk\Fake\Custom\Activitycoupon $activitycoupon
 * @property \Zacksleo\SuningSdk\Fake\Custom\Activitycoupondetail $activitycoupondetail
 * @property \Zacksleo\SuningSdk\Fake\Custom\Memlabels $memlabels
 * @property \Zacksleo\SuningSdk\Fake\Custom\Shoplabels $shoplabels
 * @property \Zacksleo\SuningSdk\Fake\Custom\Shopfavorited $shopfavorited
 * @property \Zacksleo\SuningSdk\Fake\Custom\Pricereduce $pricereduce
 * @property \Zacksleo\SuningSdk\Fake\Custom\Pricereducedetail $pricereducedetail
 * @property \Zacksleo\SuningSdk\Fake\Custom\Shopcoupdetail $shopcoupdetail
 * @property \Zacksleo\SuningSdk\Fake\Custom\Shopcoupon $shopcoupon
 * @property \Zacksleo\SuningSdk\Fake\Custom\Promotion $promotion
 * @property \Zacksleo\SuningSdk\Fake\Custom\Salesmanage $salesmanage
 * @property \Zacksleo\SuningSdk\Fake\Custom\Direcoupon $direcoupon
 * @property \Zacksleo\SuningSdk\Fake\Custom\Direcoupondetail $direcoupondetail
 * @property \Zacksleo\SuningSdk\Fake\Custom\Ordercoupon $ordercoupon
 * @property \Zacksleo\SuningSdk\Fake\Custom\Ordercoupondetail $ordercoupondetail
 * @property \Zacksleo\SuningSdk\Fake\Custom\Syncinventory $syncinventory
 * @property \Zacksleo\SuningSdk\Fake\Custom\Batchorder $batchorder
 * @property \Zacksleo\SuningSdk\Fake\Custom\Orderid $orderid
 * @property \Zacksleo\SuningSdk\Fake\Custom\Oneorder $oneorder
 * @property \Zacksleo\SuningSdk\Fake\Custom\Sendgoods $sendgoods
 * @property \Zacksleo\SuningSdk\Fake\Custom\Returngoods $returngoods
 * @property \Zacksleo\SuningSdk\Fake\Custom\Singleinventory $singleinventory
 * @property \Zacksleo\SuningSdk\Fake\Custom\Storegrouplist $storegrouplist
 * @property \Zacksleo\SuningSdk\Fake\Custom\Logisticsorder $logisticsorder
 */
class Custom
{
}
